### ISSUE TITLE
#1939 [質問]：プルリクエストが取り込まれない

### ISSUE THREAD

**Issue by mendelssohnbach** [elmas3/pull-request-practice#1943]
#1939 opened 3 days ago by mendelssohnbach

上記のプルリクエストが取り込まれないのはなぜですか？

#1939 をプルリクエストスレ前に、
#1928 by mendelssohnbach was closed 8 days ago

を close して書籍を読み直しました。
再度、プルリクエストしました。
取り込まれない理由はどのような事柄が考えられますか？

操作環境は
- Ubuntu18.04 の Live USB
- ターミナルでの操作

UbuntuではSource Treeを利用できないため、
書籍の手順を守れていないかもしれません。

**Comment by llminatoll** [comment]
@mendelssohnbach さま

ご返信が大変遅くなり失礼いたいました。
現在プルリクエストがたまりすぎており、手動でのマージが追いつかない状態です。
（1人ですべて目視確認しながらマージしております。なおマージを自動化しない理由は、稀に公序良俗に反するプルリクエストもあるためです。）

手順は問題ありませんので、Closeにしていただいているものを再びOpenにしてもらえれば古いものから順にマージして行きます。
あくまでも書籍で保証しているのは「プルリクの練習ができる」点で、マージは確実になされるものではないことをご了承いただければありがたいです。

この度は不安なお気持ちにさせてしまい誠に申し訳ありませんでした。

**Comment by mendelssohnbach** [comment]
llminatoll さま

お忙しい中、回答ありがとうございます。
状況は理解できました。
本件を close とさせていたします。

> 手順は問題ありません

とのことなので、安心しました。

#1939  について close としました。
多少なりとも負担の軽減になれば幸いです。
