### ISSUE TITLE
「elmas3」の「3」はどういう意味ですか？

### ISSUE THREAD

**Issue by ricky50575** [elmas3/pull-request-practice#3058]
「エルマスさん」？

**Comment by llminatoll** [comment]
書き込みありがとうございます！
はい、その通りです。エルマス「さん」の意味になっております😄

**Comment by ricky50575** [comment]
> 書き込みありがとうございます！
> はい、その通りです。エルマス「さん」の意味になっております😄

「3」と聞かれるとエルマスさんが恥ずかしいのはなぜですか？

**Comment by llminatoll** [comment]
ID名が「3」と「さん」を掛けていて、ダジャレになっているのを指摘されて恥ずかしがっていたみたいですね！

**Comment by llminatoll** [comment]
ご質問ありがとうございました！こちらのイシューはクローズさせていただきますね😄
